### EXAM

Karolina Binkevičiūtė

1.	Data types:
- a) What types of data exist? Provide examples.
- b) Explain in detail what characteristics each data type have.
- c) Why are there different types of data?

a) Types of Data:
Numerical Data (Quantitative)
Discrete: Countable items (e.g., number of students).
Continuous: Measurable quantities (e.g., height).
Categorical Data (Qualitative)
Nominal: Categories without order (e.g., gender).
Ordinal: Ordered categories (e.g., rankings).
Binary Data
Two possible values (e.g., yes/no).
Time Series Data
Data indexed by time (e.g., stock prices).
Spatial Data
Geographic locations (e.g., coordinates).
Text Data
Written language (e.g., reviews).
Image Data
Visual data (e.g., photographs).
b) Characteristics
Numerical Data
Discrete: Whole numbers, no fractions (e.g., number of cars).
Continuous: Any value in a range, including fractions (e.g., temperature).
Categorical Data
Nominal: No inherent order (e.g., types of fruit).
Ordinal: Ordered categories (e.g., education level).
Binary Data
Only two values (e.g., on/off).
Time Series Data
Time-dependent (e.g., daily sales).
Spatial Data
Location-specific (e.g., map points).
Text Data
Unstructured, processed via NLP (e.g., tweets).
Image Data
Pixel-based visual information (e.g., X-rays).
c) Why Different Types of Data?
Different types of data exist to capture the diversity of information we encounter. Each type suits specific analysis techniques, ensuring accurate and meaningful insights. For instance, numerical data is used for mathematical computations, while categorical data helps in classification tasks. This diversity facilitates effective data analysis, modeling, and decision-making across various fields.

2. Correlation vs causation:
- a) What is the difference between correlation and causation? 
- b) Give me an example there corelation exist but there is no causal relationship.

a) Difference Between Correlation and Causation
Correlation: Indicates a statistical relationship between two variables, meaning they change together, but does not imply that one causes the other.
Causation: Means that one event directly causes another event.
b) Example of Correlation Without Causation
Ice Cream Sales and Drowning Incidents: Both increase in the summer, showing a positive correlation. However, eating ice cream does not cause drowning. The real cause is hot weather, which leads to more people buying ice cream and swimming.

3. Implement the following formula for the following dataset:
    $$ \frac{\Sigma y_i}{\bar y} \times \frac{\Sigma x_i * \bar x}{\sigma_x}  $$
    $$ x = [10, 34, 15, 28, 34, 88, 29]$$
    $$ y = [1, 2, 3, 4, 5, 6, 7]$$

In [3]:
x = np.array([10, 34, 15, 28, 34, 88, 29])
y = np.array([1, 2, 3, 4, 5, 6, 7])
data = (np.sum(y) / np.mean(y)) * (np.sum(x) * np.mean(x) / np.std(x))
print(data)

2395.479857689225

4. You have been provided two datasets: the first one is sold orders, which has the recorded orders of each customer, and the second one is prices of the products, 
which show the prices of each product. Do the following:
- a) Import both datasets into your python enviroment
- b) Show which type of product was sold the most.
- c) Calculate how much revenue did this company made.
- d) Out of all the products, which product returned the highest revenue?
- e) Show at least three products that women prefer more than men.

In [2]:
from sympy import Symbol, Derivative
from sympy import Symbol
import matplotlib
import numpy as np
import pandas as pd

In [4]:
orders = pd.read_csv('orders.csv')
print(orders)

        Unnamed: 0  User ID Country         City   Street  Day     Sex  \
0                0        1  Canada      Toronto   Elm St   28  Female
1                1        2  Canada  Mexico City  Main St   10    Male
2                2        3  Mexico      Toronto   Elm St   12  Female
3                3        4     USA      Toronto   Oak St    6  Female
4                4        5  Canada      Toronto   Elm St    3    Male
...            ...      ...     ...          ...      ...  ...     ...
199995      199995   199996     USA     New York  Main St    7  Female
199996      199996   199997  Canada  Mexico City  Main St    9  Female
199997      199997   199998     USA      Toronto   Oak St   29  Female
199998      199998   199999     USA      Toronto  Main St    8  Female
199999      199999   200000     USA  Mexico City   Oak St   14  Female

         Product  Quantity
0         Banana         8
1         Banana         8
2          Lemon         6
3           Date         8
4       Honeydew         5
...          ...       ...
199995  Honeydew         3
199996    Banana         7
199997     Grape         6
199998     Grape         7
199999  Honeydew         6

[200000 rows x 9 columns]

In [5]:
orders[['Product','Quantity']]

         Product  Quantity
0         Banana         8
1         Banana         8
2          Lemon         6
3           Date         8
4       Honeydew         5
...          ...       ...
199995  Honeydew         3
199996    Banana         7
199997     Grape         6
199998     Grape         7
199999  Honeydew         6

[200000 rows x 2 columns]

In [6]:
prices = pd.read_csv('prices.csv')
print(prices)

   Unnamed: 0       Fruit  Price
0           0  Elderberry   3.00
1           1       Apple   2.50
2           2        Kiwi   6.00
3           3        Date   1.40
4           4      Banana   3.00
5           5    Honeydew   1.20
6           6       Lemon   2.30
7           7      Cherry   4.20
8           8       Grape   0.22
9           9         Fig   0.33

In [7]:
product = orders['Product'].value_counts().idxmax()
product

'Apple'

In [8]:
merged = pd.merge(orders,prices, left_on='Product', right_on='Fruit')
merged

,Unnamed: 0_x,User ID,Country,City,Street,Day,Sex,Product,Quantity,Unnamed: 0_y,Fruit,Price
0,0,1,Canada,Toronto,Elm St,28,Female,Banana,8,4,Banana,3.00
1,1,2,Canada,Mexico City,Main St,10,Male,Banana,8,4,Banana,3.00
2,2,3,Mexico,Toronto,Elm St,12,Female,Lemon,6,6,Lemon,2.30
3,3,4,USA,Toronto,Oak St,6,Female,Date,8,3,Date,1.40
4,4,5,Canada,Toronto,Elm St,3,Male,Honeydew,5,5,Honeydew,1.20
...,...,...,...,...,...,...,...,...,...,...,...,...
199995,199995,199996,USA,New York,Main St,7,Female,Honeydew,3,5,Honeydew,1.20
199996,199996,199997,Canada,Mexico City,Main St,9,Female,Banana,7,4,Banana,3.00
199997,199997,199998,USA,Toronto,Oak St,29,Female,Grape,6,8,Grape,0.22
199998,199998,199999,USA,Toronto,Main St,8,Female,Grape,7,8,Grape,0.22
199999,199999,200000,USA,Mexico City,Oak St,14,Female,Honeydew,6,5,Honeydew,1.20

In [14]:
merged['Revenue'] = merged['Price'] * merged['Quantity'] 
merged

,Unnamed: 0_x,User ID,Country,City,Street,Day,Sex,Product,Quantity,Unnamed: 0_y,Fruit,Price,Revenue
0,0,1,Canada,Toronto,Elm St,28,Female,Banana,8,4,Banana,3.00,24.00
1,1,2,Canada,Mexico City,Main St,10,Male,Banana,8,4,Banana,3.00,24.00
2,2,3,Mexico,Toronto,Elm St,12,Female,Lemon,6,6,Lemon,2.30,13.80
3,3,4,USA,Toronto,Oak St,6,Female,Date,8,3,Date,1.40,11.20
4,4,5,Canada,Toronto,Elm St,3,Male,Honeydew,5,5,Honeydew,1.20,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,199995,199996,USA,New York,Main St,7,Female,Honeydew,3,5,Honeydew,1.20,3.60
199996,199996,199997,Canada,Mexico City,Main St,9,Female,Banana,7,4,Banana,3.00,21.00
199997,199997,199998,USA,Toronto,Oak St,29,Female,Grape,6,8,Grape,0.22,1.32
199998,199998,199999,USA,Toronto,Main St,8,Female,Grape,7,8,Grape,0.22,1.54
199999,199999,200000,USA,Mexico City,Oak St,14,Female,Honeydew,6,5,Honeydew,1.20,7.20

In [16]:
total_revenue = merged.groupby('Product')['Revenue'].sum().sum()
print(total_revenue)

2417051.2

In [17]:
highest_revenue = merged.groupby('Product')['Revenue'].sum().sort_values(ascending=False).head(1)
highest_revenue

Product
Kiwi    599130.0
Name: Revenue, dtype: float64

In [18]:
product_sex_preferences = merged.groupby(['Product', 'Sex'])['Quantity'].sum().unstack()
product_sex_preferences['Difference'] = product_sex_preferences['Female'] - product_sex_preferences['Male']
products_preferred_by_women = product_sex_preferences[product_sex_preferences['Difference'] > 0]
top_three_products_preferred_by_women = products_preferred_by_women.sort_values(by='Difference', ascending=False).head(3)

top_three_products_preferred_by_women

Sex       Female   Male  Difference
Product
Honeydew   50420  48884        1536
Banana     50665  49605        1060
Cherry     50427  49466         961

5.	According to a study that was conducted by the University of Michigan that analyzed 6.5 million car crashes it was found that women were involved in 68.7% of all car crashes. Is the study correct to assume that women are bad drivers? Provide counter-evidence why this study might have been wrong?

The conclusion that women are bad drivers based solely on the statistic that women were involved in 68.7% of all car crashes from the University of Michigan study is an oversimplification and potentially misleading.
Women might be involved in more minor fender-benders and low-speed collisions, which could inflate their involvement numbers without indicating poor driving skills
Women may file more insurance claims, but these tend to be for less severe accidents compared to men.
Men tend to drive more miles annually compared to women. This increased exposure could mean that men have more opportunities to get into accidents, yet their higher mileage isn't always reflected in the number of accidents.
Also not all the data is known because for example it doesnt't say how old the women in the study are, because the older you get, the less concentracion you have, so that means more car crashes could be done. Maybe the men that were in the study was not old enough compared to the women's. 
Another thing is that it doesn't tell how big of the crashes were made, because maybe the analysis was concluded from only minor fender-benders and not the big crashes.